src/config/routes.rb
# Project name: ACCR Mail Manager
# Description: Mail database and management system for ACCR community partner
# Filename: routes.rb
# Description: Configuration file for Rails page routes
# Last modified on: 3/26/23
# Code written by Team 13, Team 14, and Team 24

# Project name: AMSTR
# Description: ACCR Management System Tracker
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options
# Last modified on: 4/13/22

# Project name: Call Organizer
# Description: This project will keep track of the various calls ACCR recieves.
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options.
# Last modified on: 04/23/2023

# frozen_string_literal: true


# frozen_string_literal: true
# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

   get 'calls_home/index'
  resources :calls

  
  get 'speaker/all'
  get 'speaker/delete'
  post 'speaker/show'
  post 'webinars/deregisterSubmitted'
  get 'webinars/deregisterSubmitted'
  get 'speaker/new'
  post 'speaker/created'

  get 'requests/viewrequests'
  get 'webinars/deregister'
  

  resources :requests

  get 'webinars/exportCSV'
  post 'webinars/exportCSV'


  get 'charges/new'
  get 'charges/create'
  post 'exportCSV', to: 'webinars#exportCSV', as: 'exportCSV'

# delete from here if problem

  resources :donors
  resources :donars
  get 'in_kinds_home/index'
  get 'inkinds/index'


  
  resources :inkinds  do
    collection do
      get 'download_pdf'
    end
  end


  #pro-bono donations
  get 'donations/donations'
  get '/donations.csv' => 'donations#index'
  match 'donations', to: 'donations#donations', via: 'get'
  resources :donations do
    collection do
      post :import
    end
  end

  resources :event_details
  get 'calendar/calendar'

# to here

  resources :registrants
  resources :responses
  resources :reminders
  resources :webinars do
    member do
      get :registrants
    end
  end
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'webinars/index'
  get 'webinars/about'
  # does not need devise login
  # get 'webinarjoin', to: "webinarjoin#index"
  

  # routes for speaker information page
  get 'speaker/index'

  # The root page is set for the index.
  ### root 'home#index'
  get 'mail_manager_home/index'

  # Routes for pages other than the root.
  get 'mail_manager_home/about'

  # All pages associated with mail_entries and tags scaffold.
  resources :mail_entries
  resources :tags

  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # Custom routes for adding / deleting tags en masse.
  post 'delete_selected' => 'tags#delete_selected'
  post 'create_entered' => 'tags#create_entered'
  # post 'tag_filter' => 'mail_entries#'


  get 'statistics/index'
  resources :worklogs
  resources :projects

  resources :searches do
    get "search", on: :collection
  end

  root 'nav#home'

  get 'dashboard/dash'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard/dash'
  get 'dashboard/view_report'
  get 'home/index'
  get 'report/index'
  get 'dashboard/aboutus'


  

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  post "/map/index" => "map#index"
  # root 'home#index'
  get 'mapping_justice_home/index'
  get 'map/graph'
  get 'map/index'
  get 'about/index'
  get 'upload/index'
  post 'upload/uploadcsv'
  get 'upload/downloadcsv'
  get 'upload/edit'
  post 'upload/update'
  patch 'upload/:format', to: 'upload#update'
  get 'upload/destroy'
  #patch 'upload/:format', to: 'upload#destroy'

  #Used for clearing sorting
  get "/donations/clear_sort", to: "donations#clear_sort", as: "clear_sort"
  
  get "/donations/filtering", to: "donations#filtering", as: "filtering"

  get 'in_kinds_home/index'
  get 'donors/index'
  # Used for webinar registration forms
  get 'registrants/new' # Links to form input page
  get 'registrants/index'
  post 'registrants/new', to: 'registrants#create' # Creates post route for submitting form
  patch 'registrants/:id/activate',to:'registrants#activate' , as: :activate
  patch 'registrants/:id/deactivate',to:'registrants#deactivate' ,as: :deactivate
  
  get '/payment', to: 'payment_controller#blank_page'
  
  
    #get '/', to: 'register#index'
    #post '/orders/submit', to: 'orders#submit'
  
  # Devise authentification pages. This controlls the user login
  # and authentification system.

  # commented out due to rake aborted error
  # devise_for :users

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  #root 'home#index'

  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'

  # stripe
  resources :charges, only: [:new, :create, :thanks]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  
end

src/app/models/request.rb
class Request < ApplicationRecord
end

src/app/controllers/requests_controller.rb
=begin
Project name: ACCR Webinar
Description: This project will keep track of the webinars and their respective speakers.
Filename: requests_controller.rb
Description: Handles creation and updating of a new request and validates appropriately.
Last modified on: April 22, 2023
=end

class RequestsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  def viewrequests
    @requests = Request.all
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)
    if request_params[:first_name].squish.empty?
      @request.errors.add(:first_name, "cannot be blank.")
    end
    if request_params[:last_name].squish.empty?
      @request.errors.add(:last_name, "cannot be blank.")
    end
    if request_params[:email].squish.empty?
      @request.errors.add(:email, "cannot be blank.")
    end
    if request_params[:request].squish.empty?
      @request.errors.add(:request, "cannot be blank.")
    end

    respond_to do |format|
      if @request.errors.none? && @request.save
        format.html { redirect_to request_url(@request), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_viewrequests_url, notice: "Request was successfully destroyed." }

      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:first_name, :last_name, :email, :request)
    end
end

src/app/helpers/requests_helper.rb
module RequestsHelper
end

src/app/views/requests/_form.html.erb
<% if request.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>
    <ul>
      <% request.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: request, local: true) do |form| %>
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :request %>
    <%= form.text_field :request %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |

<%= link_to 'Back', requests_viewrequests_path %>

src/app/views/requests/index.html.erb
<div class="jumbotron">
    <h3 class="text-center display-4">Webinars</h3>
    <p class="text-center lead">
      The webinars module contains upcoming and past webinars. 
      Click the button below to view the webinars!
    </p>
    <p class="text-center">
        <a  style ="color:white;" class="btn btn-primary btn-lg"<%= link_to 'View Webinars', webinars_path%></a>
    </p>
</div>


<% if can?(:access, :rails_admin) %>
<div class="jumbotron">
    <h3 class="text-center display-4">Requests</h3>
    <p class="text-center lead">
      Click the button below to view requests for webinars.
    </p>
    <p class="text-center">
        <a  style ="color:white;" class="btn btn-primary btn-lg"<%= link_to 'View Requests',requests_viewrequests_path %></a>
    </p>
</div>

<div class="jumbotron">
    <h3 class="text-center display-4">Speakers</h3>
    <p class="text-center lead">
      View, Delete, and Create Speakers here.
    </p>
    <p class="text-center">
        <a  style ="color:white;" class="btn btn-primary btn-lg"<%= link_to 'View Speakers', speaker_all_path%></a>
    </p>
</div>

<% else %>
<div class="jumbotron">
    <h3 class="text-center display-4">Requests</h3>
    <p class="text-center lead">
      Missed a webinar that you would like to see happen again or have an idea for a webinar? <br>
      Click the button below to creat a request.
    </p>
    <p class="text-center">
        <a  style ="color:white;" class="btn btn-primary btn-lg"<%= link_to 'New Request', new_request_path%></a>
    </p>
</div>
<%end %>


    

src/app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

src/app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @request.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @request.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @request.email %>
</p>

<p>
  <strong>Request:</strong>
  <%= @request.request %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |

<%= link_to 'Back', requests_viewrequests_path %>

src/app/views/requests/viewrequests.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Request</th>
      <th colspan="100%"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request|  %>
      <tr>
        <td><%= request.first_name %></td>
        <td><%= request.last_name %></td>
        <td><%= request.email %></td>
        <td><%= request.request %></td>
        <td><%= link_to 'Show', request, class:'btn btn-primary' %></td>
        <td><%= link_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary'  %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>