src/config/routes.rb
# Project name: ACCR Mail Manager
# Description: Mail database and management system for ACCR community partner
# Filename: routes.rb
# Description: Configuration file for Rails page routes
# Last modified on: 3/26/23
# Code written by Team 13, Team 14, and Team 24

# Project name: AMSTR
# Description: ACCR Management System Tracker
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options
# Last modified on: 4/13/22

# Project name: Call Organizer
# Description: This project will keep track of the various calls ACCR recieves.
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options.
# Last modified on: 04/23/2023

# frozen_string_literal: true


# frozen_string_literal: true
# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

   get 'calls_home/index'
  resources :calls

  
  get 'speaker/all'
  get 'speaker/delete'
  post 'speaker/show'
  post 'webinars/deregisterSubmitted'
  get 'webinars/deregisterSubmitted'
  get 'speaker/new'
  post 'speaker/created'

  get 'requests/viewrequests'
  get 'webinars/deregister'
  

  resources :requests

  get 'webinars/exportCSV'
  post 'webinars/exportCSV'


  get 'charges/new'
  get 'charges/create'
  post 'exportCSV', to: 'webinars#exportCSV', as: 'exportCSV'

# delete from here if problem

  resources :donors
  resources :donars
  get 'in_kinds_home/index'
  get 'inkinds/index'


  
  resources :inkinds  do
    collection do
      get 'download_pdf'
    end
  end


  #pro-bono donations
  get 'donations/donations'
  get '/donations.csv' => 'donations#index'
  match 'donations', to: 'donations#donations', via: 'get'
  resources :donations do
    collection do
      post :import
    end
  end

  resources :event_details
  get 'calendar/calendar'

# to here

  resources :registrants
  resources :responses
  resources :reminders
  resources :webinars do
    member do
      get :registrants
    end
  end
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'webinars/index'
  get 'webinars/about'
  # does not need devise login
  # get 'webinarjoin', to: "webinarjoin#index"
  

  # routes for speaker information page
  get 'speaker/index'

  # The root page is set for the index.
  ### root 'home#index'
  get 'mail_manager_home/index'

  # Routes for pages other than the root.
  get 'mail_manager_home/about'

  # All pages associated with mail_entries and tags scaffold.
  resources :mail_entries
  resources :tags

  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # Custom routes for adding / deleting tags en masse.
  post 'delete_selected' => 'tags#delete_selected'
  post 'create_entered' => 'tags#create_entered'
  # post 'tag_filter' => 'mail_entries#'


  get 'statistics/index'
  resources :worklogs
  resources :projects

  resources :searches do
    get "search", on: :collection
  end

  root 'nav#home'

  get 'dashboard/dash'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard/dash'
  get 'dashboard/view_report'
  get 'home/index'
  get 'report/index'
  get 'dashboard/aboutus'


  

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  post "/map/index" => "map#index"
  # root 'home#index'
  get 'mapping_justice_home/index'
  get 'map/graph'
  get 'map/index'
  get 'about/index'
  get 'upload/index'
  post 'upload/uploadcsv'
  get 'upload/downloadcsv'
  get 'upload/edit'
  post 'upload/update'
  patch 'upload/:format', to: 'upload#update'
  get 'upload/destroy'
  #patch 'upload/:format', to: 'upload#destroy'

  #Used for clearing sorting
  get "/donations/clear_sort", to: "donations#clear_sort", as: "clear_sort"
  
  get "/donations/filtering", to: "donations#filtering", as: "filtering"

  get 'in_kinds_home/index'
  get 'donors/index'
  # Used for webinar registration forms
  get 'registrants/new' # Links to form input page
  get 'registrants/index'
  post 'registrants/new', to: 'registrants#create' # Creates post route for submitting form
  patch 'registrants/:id/activate',to:'registrants#activate' , as: :activate
  patch 'registrants/:id/deactivate',to:'registrants#deactivate' ,as: :deactivate
  
  get '/payment', to: 'payment_controller#blank_page'
  
  
    #get '/', to: 'register#index'
    #post '/orders/submit', to: 'orders#submit'
  
  # Devise authentification pages. This controlls the user login
  # and authentification system.

  # commented out due to rake aborted error
  # devise_for :users

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  #root 'home#index'

  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'

  # stripe
  resources :charges, only: [:new, :create, :thanks]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  
end

src/app/models/inkind.rb
=begin
    Project Name: InKind Donations
    FileName:/home/student5/RoJ-Spr23/src/app/models/inkind.rb
    Description: Inkind model, with data validation, and nested inkindentries attribute
    Last Modified: April 27, 2023
=end


class Inkind < ApplicationRecord
  belongs_to :donor
  has_many :inkindentries, dependent: :destroy
  accepts_nested_attributes_for :inkindentries

  # TODO: Add length limits for all fields.

  # Ensures that the date field is a valid date.

  validates :date, presence: true
  validate :validate_date_format

  # The "presence: true" part ensures that the corresponding field
  # is nonempty. So this should only be done for mandatory fields.
  validates :name, presence: true
   
  validates :donor_name, presence: true
   
  # csv function that outputs csv
  def self.to_csv
    attributes = %w{Name Date Hours Value Description User Genre Donor}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |inkind|
        #string variables to handle situations with multiple entries and print to csv
        value_str = inkind.inkindentries.map { |donation| donation.value.to_s }.join(';')
        desc_str = inkind.inkindentries.map { |donation| donation.description.to_s }.join(';')
        hours_str = inkind.inkindentries.select { |donation| donation.hours.present? }.map { |donation| donation.hours.to_s }.join(';')
        csv << [inkind.name, inkind.date, hours_str, value_str, desc_str, inkind.user, inkind.genre, inkind.donor_name]
      end
    end
  end

  #function to ensure date has actually occurred
  def validate_date_format
    if date.present? && date >= Date.today
      errors.add(:date, "entered has not happened yet")
    end
  end    
end

src/app/controllers/inkinds_controller.rb
class InkindsController < ApplicationController
  before_action :set_inkind, only: %i[ show edit update destroy ]
  

  # GET /inkind or /inkind.json
  def index
    params.permit(:search)

    _searchParam = params[:search]
    if (_searchParam != nil)
      @inkinds = Inkind.search(_searchParam)
    else
      @inkinds = Inkind.all()
    end
    # @inkinds = Inkind.all

    respond_to do |format|
      format.html
      format.csv { send_data @inkinds.to_csv, filename:"IK_report.csv"}
    end
  end

  # GET /inkind/1 or /inkind/1.json
  def show
  end

  # GET /inkind/new
  def new
    @inkind = Inkind.new
    @inkind.inkindentries.build
    @inkind.donor_name = "";
    @inkind.donor_id = 0;
    @donor_names = Donor.pluck(:donor_name)
  end

  # GET /inkind/1/edit
  def edit
    @donor_names = Donor.pluck(:donor_name)
  end

  # POST /inkind or /inkind.json
  def create
    
    donor = Donor.find_by(donor_name: inkind_params[:donor_name])
    inkind_params_with_donor_id = inkind_params.merge(donor_id: donor.id) if donor.present?
    @inkind = Inkind.new(inkind_params_with_donor_id)

    respond_to do |format|
      if @inkind.save

        format.html { redirect_to inkind_url(@inkind), notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @inkind }
      else
        @donor_names = Donor.pluck(:donor_name)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inkind.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /inkind/1 or /inkind/1.json
  def update
    respond_to do |format|
      if @inkind.update(inkind_params)
        format.html { redirect_to inkind_url(@inkind), notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @inkind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inkind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inkind/1 or /inkind/1.json
  def destroy
    @inkind.destroy

    respond_to do |format|
      format.html { redirect_to inkinds_url, notice: "Donation was successfully removed." }
      format.json { head :no_content }
    end
  end


  #Searches for a certain string based on all pro-bono hour donations
  def inkinds


  
  #Downloads a pdf of a particular in kind donation
  def download_pdf

    pdf = Prawn::Document.new
    pdf.font "Times-Roman"

    inkind = Inkind.find(params[:id])

    #rendering the template image
    pdf.image "#{Rails.root}/app/assets/images/inkind_template.png", at: [0, 730],  width: 530


    #local variables
    project_name = inkind.name
    donor_organization = inkind.donor_name
    address = inkind.donor.location
    phone_number = inkind.donor.phoneNumber
    date_of_service = inkind.date.strftime("%B %d, %Y")
    approvee_name = "Gregory  Johnson"
    approvee_title = "Director of Operations"
    date_approved = Date.today
    services_type = inkind.genre
    inkind_entries = inkind.inkindentries
    total_services = 0
    total_goods = 0
    total_facilities = 0
    total_value = 0

    pdf.font 'Times-Roman'
  
    #drawing the PDF entries onto the PDF
    pdf.draw_text "Atlantic Center for Capital Representation", at: [198, 635]
    pdf.draw_text project_name, at: [50, 608]
    pdf.draw_text donor_organization, at: [110, 595]
    pdf.draw_text address, at: [57, 582]
    pdf.draw_text phone_number, at: [340, 556]
    pdf.draw_text date_of_service, at: [150, 503]
    
    pdf.draw_text approvee_name, at: [150, 130]
    pdf.draw_text approvee_title, at: [150, 117]
    pdf.draw_text date_approved, at: [150, 104]  
    
      
    if services_type == "service"
      pdf.text_box "N.A.", at: [85, 362], align: :left
      pdf.text_box "N.A.", at: [100, 270], align: :left
      y_position = 467
      inkind_entries.each do |inkind_entry|
        name = inkind_entry.description
        hours = inkind_entry.hours
        cost = inkind_entry.value
        [["#{name}", 70], ["#{hours}", 305], ["#{cost}", 400]].each do |text, x_position|
          pdf.text_box text, at: [x_position, y_position], align: :left
        end
        total_services += cost.to_i
        y_position -= 13
      end
      total_value = total_services
      pdf.draw_text total_services, at: [396, 381] 
      pdf.draw_text "N.A.", at: [396, 287]
      pdf.draw_text "N.A.", at: [396, 183]  
 
    elsif services_type == "good(s)"
      pdf.text_box "N.A.", at: [96, 481], align: :left
      pdf.text_box "N.A.", at: [100, 270], align: :left
      y_position = 350
      inkind_entries.each do |inkind_entry|
        name = inkind_entry.description
        cost = inkind_entry.value
        [["#{name}", 70], ["#{cost}", 400]].each do |text, x_position|
          pdf.text_box text, at: [x_position, y_position], align: :left
        end
        total_goods += cost.to_i
        y_position -= 13
      end
      total_value = total_goods
      pdf.draw_text "N.A.", at: [396, 381] 
      pdf.draw_text total_goods, at: [396, 287]
      pdf.draw_text "N.A.", at: [396, 183]  

    elsif services_type == "facility"
      pdf.text_box "N.A.", at: [96, 481], align: :left
      pdf.text_box "N.A.", at: [85, 362], align: :left
      y_position = 257
      inkind_entries.each do |inkind_entry|
        place = inkind_entry.description
        cost = inkind_entry.value
        [["#{place}", 70], ["#{cost}", 400]].each do |text, x_position|
          pdf.text_box text, at: [x_position, y_position], align: :left
        end
        total_facilities += cost.to_i
        y_position -= 13
      end
      total_value = total_facilities
      pdf.draw_text "N.A.", at: [396, 381] 
      pdf.draw_text "N.A.", at: [396, 287]
      pdf.draw_text total_facilities, at: [396, 183]  
    end

    pdf.draw_text total_value, at: [396, 170]  
    send_data pdf.render, filename: "hello.pdf", type: "application/pdf", disposition: "inline"

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inkind
      @inkind = Inkind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inkind_params
      params.require(:inkind).permit(:name, :date, :value, :hours, :description, :user, :genre, :donor_name, :donor_id, inkindentries_attributes: [:id, :description, :hours, :value])
    end

  end
end

src/app/helpers/inkinds_helper.rb
module InkindsHelper
end

src/app/views/inkinds/_form.html.erb
<% 
=begin
    Project Name: InKind Donations
    FileName:/home/student5/RoJ-Spr23/src/app/views/inkinds/_form.html.erb
    Description: Displays the Edit functionality for the Inkind. Javascript usedto dynamically displaly fields based on genre of inkind
    Last Modified: April 26, 2023
=end
%>

<%= javascript_tag do %>
<%# Add event listener for when the DOM content has been loaded %>
  document.addEventListener('DOMContentLoaded', function() {
    <%# Get the genre select dropdown element %>
    const genreSelect = document.getElementById('inkind_genre');
    
    <%# Function to show or hide the hours field for a given row %>
    function toggleHoursFieldForRow(row) {
      const hoursField = row.querySelector('.hours-field');  

      <%# Show the hours field if the selected genre is 'service', else hide it %>
      if (genreSelect.value === 'service') {
        hoursField.style.display = 'block';
      } else {
        hoursField.style.display = 'none';
      }
    }

    <%# Function to show or hide the hours field for all rows %>
    function toggleHoursFieldForAllRows() {
      <%#  Get all fields-row elements %>
      const rows = document.querySelectorAll('.fields-row');
      <%# Call toggleHoursFieldForRow for each row %>
      rows.forEach((row) => toggleHoursFieldForRow(row));
    }

    <%# Add event listener to the genre select element to toggle hours field visibility on change %>
    genreSelect.addEventListener('change', toggleHoursFieldForAllRows);

    <%# Add event listener to the 'add-additional' button to clone a row %>
    document.getElementById('add-additional').addEventListener('click', function(event) {
      event.preventDefault();
      const fieldsToClone = document.querySelector('.clone-fields');
      const clonedFields = fieldsToClone.cloneNode(true);
      <%# Insert the cloned fields before the add-additional-wrapper element %>
      fieldsToClone.parentElement.insertBefore(clonedFields, document.getElementById('add-additional-wrapper'));

      <%#  Calculate the new index for the cloned row %>
      const newIndex = document.querySelectorAll('.fields-row').length - 1;
      <%#  Define patterns for replacing ID and name attributes %>
      const idPattern = /inkind_inkindentries_attributes_\d+_/;
      const namePattern = /inkind\[inkindentries_attributes\]\[\d+\]/;
      <%#  Update ID, name, and for attributes for all input, label, and select elements within the cloned fields %>
      clonedFields.querySelectorAll('input, label, select').forEach(function (element) {
        if (element.hasAttribute('id')) {
          element.setAttribute('id', element.getAttribute('id').replace(idPattern, `inkind_inkindentries_attributes_${newIndex}_`));
        }
        if (element.hasAttribute('name')) {
          element.setAttribute('name', element.getAttribute('name').replace(namePattern, `inkind[inkindentries_attributes][${newIndex}]`));
        }
        if (element.tagName === 'LABEL') {
          element.setAttribute('for', element.getAttribute('for').replace(idPattern, `inkind_inkindentries_attributes_${newIndex}_`));
        }
      });

      <%#  Toggle hours field visibility for the cloned row %>
      toggleHoursFieldForRow(clonedFields.querySelector('.fields-row'));
      <%#  Show the 'delete-additional' button %>
      document.getElementById('delete-additional').style.display = 'inline';
    });

    <%#  Add event listener to the 'delete-additional' button to remove the last row %>
    document.getElementById('delete-additional').addEventListener('click', function(event) {
      event.preventDefault();
      const fields = document.querySelectorAll('.fields-row');
      const lastField = fields[fields.length - 1];
      lastField.remove();
      <%# Hide the "Delete additional" button when there is only one remaining "fields-row" after deletion %>
      if (fields.length === 2) {
        document.getElementById('delete-additional').style.display = 'none';
      }
    });

    toggleHoursFieldForAllRows();
  });
<% end %>

<%= form_with(model: inkind, local: true) do |form| %>
  <% if inkind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inkind.errors.count, "error") %> prohibited this inkind from being saved:</h2>

      <ul>
        <% inkind.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name, "Project Name" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date, "Date" %>
    <%= form.date_field :date %>
  </div>
  <div style="font-size: 0.8em;"><b> (Selecting Service from dropdown will create field for hours) </b> </div>
   <div class="field">
    <%= form.label :type %>
    <%# Dropdown for selecting the type good(s), facility, or service %>
    <%= form.select(:genre, options_for_select([["good(s)", "good(s)"], ["facility", "facility"], ["service", "service"]])) %> 
  </div>
   <div style="font-size: 0.8em;"><b> (When adding value to an entry, value should be entered as total hours) </b> </div>
  <%# Container for cloning fields-row elements %>
  <div class="clone-fields">
  <%# Nested inkindentries attribute form for values, description, and hours %>
  <%= form.fields_for :inkindentries do |description_fields| %> 
    <div class="fields-row">
      <div class="field">
        <%= description_fields.label :description %>
        <%= description_fields.text_field :description %>
      </div>
      <div class="field hours-field" style="margin-left: 0.5em">
        <%= description_fields.label :hours %>
        <%= description_fields.number_field :hours, min: 0, step: 0.5 %>
      </div>
      <div class="field " style="margin-left: 0.5em">
        <%= description_fields.label :"Value \($\)" %>
        <%= description_fields.number_field :value, min: 0 %>
      </div>
    </div>
    <% end %>
  </div>
  <%# Hides add additional button fromm edit page %>
  <% if inkind.new_record? %>
    <div id="add-additional-wrapper">
      <%= link_to "Add additional", "#", id: "add-additional" %>
      <%= link_to "Delete additional", "#", id: "delete-additional", style: "display: none;" %>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :user, value: current_user.email, type: :hidden%>
  </div>

  <%# Donor field for selecting a donor from the list of donor names %>
  <div class="field">
    <%= form.label :donor %>
    <%= form.select(:donor_name, @donor_names ? options_for_select(@donor_names) : '' )%>
  </div>

  <%#TODO: Bad UI: This will remove any progress they've made, and
  doesn't give them an easy way to get back to this page.%>
  <div>
	<%= link_to "Go to \"New Donor\" page", new_donor_path %>
  </div>

  <div class="field">
    <%= form.text_field :donor_id, type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/inkinds/edit.html.erb
<style>
body {
    font-family: Helvetica;
}

h1 {
  color: rgb(34,0,155);
  text-align: left;
  font-weight: bold;
}

</style>

<h1>Editing Donation</h1>

<%= render 'form', inkind: @inkind %>


<%= link_to 'Show', @inkind %> |
<%= link_to 'Back', inkinds_path %>

src/app/views/inkinds/index.html.erb
<%#
  Project name: ACCR In Kinds Donations
  Description: In Kind Donation Manager
  Filename: index.html.erb
  Description: Page used to display in kind donations
  Last modified on: 3/29/23
  Code written by Team 14

%>

<style>
body {
    font-family: Helvetica;
}

h1 {
  color: rgb(34,0,155);
  text-align: left;
  font-weight: bold;
}

p {
  font-family: verdana;
  font-size: 20px;
}

.btn-indigo {
  color: rgb(255, 255, 255);
  background-color: rgb(34,0,155);
  border-color: rgb(34,0,155);
  text-align: left;
}

.btn-lightBlue {
  color: rgb(255, 255, 255);
  background-color: rgb(48, 140, 190);
  border-color: rgb(48, 140, 190);
  text-align: center;
}

.btn-darkBlue {
  color: rgb(255, 255, 255);
  background-color: rgb(48, 96, 152);
  border-color: rgb(48, 96, 152);
  text-align: right;
}

</style>

<h1> In-Kind Donation List</h1>
<br>

<div class="container">

  <div class="row">
    <div class="col text-left">

      <%# Allow the user to search by description (or :desc_summary) in the database %>
      <section class="search-form">


      <%# Iterate through the donations and search for user's entry by indicated text field tag  %>
        <%= form_tag(inkinds_path, method: :get) do %>
          <div class="input-group input-group-lg">
            <%= label_tag(:search, params[:search], class: "sr-only") %>
            <%= text_field_tag(:search, params[:search], placeholder: "Type here to search", class: "form-control input-lg") %>
            <span class="input-group-btn">
              <%= submit_tag("Search", name: nil, class: "btn btn-primary btn-lg") %>
            </span>
          </div>
        <%end%>
      </section>
      <br>
    </div>
  </div>

  <br>


<table class="table table-striped table-bordered table-hover" data-toggle="table">
  <thead>
    <tr>
      <th data-field="name" data-sortable="false">Name</th>
      <th data-field="date" data-sortable="true" data-sorter="dateSorter">Date</th>
      <th data-field="user" data-sortable="true">User</th>
      <th data-field="type" data-sortable="false">Type</th>
      <th data-field="value" data-sortable="false">Value</th>
      <th data-field="hours" data-sortable="false">Hours</th>
      <th data-field="desc" data-sortable="false">Description</th>
      <th data-field="donor" data-sortable="true">Donor</th>
	  <th></th>
	  <th></th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inkinds.each do |inkind|%>
      <tr>
        <td><%= link_to inkind.name, inkind %></td>
        <td><%= inkind.date.strftime("%m/%d/%Y") %></td>
        <td><%= inkind.user %></td>
        <td><%= inkind.genre %></td>
        <td>
          <% inkind.inkindentries.each do |inkind_des| %>
            <%= number_to_currency(inkind_des.value, unit: "$") %>
            <br>
          <% end %>
        </td>
        <td>
          <% inkind.inkindentries.each do |inkind_des| %>
            <%= inkind_des.hours.present? ? "#{inkind_des.hours}" : "" %>
            <br>
          <% end %>
        </td>
        <td>
          <% inkind.inkindentries.each do |inkind_des| %>
            <%= inkind_des.description %>
            <br>
          <% end %>
        </td> 
        <td><%= inkind.donor_name %></td>
        <td><%= link_to 'Download PDF', download_pdf_inkinds_path(inkind, id: inkind.id), class: "button", target: "_blank" %></td>
        <td><%= link_to 'Edit', edit_inkind_path(inkind) %></td>
        <td><%= link_to 'Remove', inkind, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <% end %>
    </thead>

    <tbody>
      <% @inkinds.each do |inkind|%>
        <tr>
          <td><%= inkind.name %></td>
          <td><%= inkind.date %></td>
          <td><%= inkind.value %></td>
          <td><%= inkind.description %></td>
          <td><%= inkind.user %></td>
          <td><%= inkind.genre %></td>
          <td><%= inkind.donor_name %></td>
          <td><%= link_to 'Show', inkind %></td>
          <td><%= link_to 'Edit', edit_inkind_path(inkind) %></td>
          <td><%= link_to 'Remove', inkind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Donation', new_inkind_path, class: "btn btn-indigo text-center" %>

  <%= link_to 'View/Edit Donors', donors_path, class: "btn btn-lightBlue text-center" %>


<%= link_to "Download CSV Report" , inkinds_path(format: "csv"), class: "btn btn-darkBlue text-center" %>

<script>
//function to sort dates after string conversion
  function dateSorter(a, b) {
    const dateA = new Date(a);
    const dateB = new Date(b);

    if (dateA < dateB) return -1;
    if (dateA > dateB) return 1;
    return 0;
  }
</script>

src/app/views/inkinds/new.html.erb
<style>
body {
    font-family: Helvetica;
}

h1 {
  color: rgb(34,0,155);
  text-align: left;
  font-weight: bold;
}

</style>

<h1>New Donation</h1>

<%= render 'form', inkind: @inkind %>

<%= link_to 'Back', inkinds_path %>

src/app/views/inkinds/show.html.erb
<% 
=begin
    Project Name: InKind Donations
    FileName:/home/student5/RoJ-Spr23/src/app/views/inkinds/_show.html.erb
    Description: Displays the show functionality for the Inkind. Displays multiple donations, and the date in a specific format
    Last Modified: April 26, 2023
=end
%>

<style>
body {
    font-family: Helvetica;
}

h1 {
  color: rgb(34,0,155);
  text-align: left;
  font-weight: bold;
}

</style>

<p id="notice"><%= notice %></p>

<h1>Donation Details</h1>

<p>
  <strong>Name:</strong>
  <%= @inkind.name %>
</p>

<p>
  <strong>Date:</strong>
  <%# turns date to string displayed as MM/DD/YYYY %>
  <%= @inkind.date.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>Description:</strong>
  <%# iterates through inkindentry for this field %>
  <% @inkind.inkindentries.each do |donation| %>
    <%= donation.description %>
    <br>
  <% end %>
</p>

<p>
  <strong>Value:</strong>
  <%# iterates through inkindentry for this field %>
  <% @inkind.inkindentries.each do |donation| %>
    <%= number_to_currency(donation.value, unit: "$") %>
    <br>
  <% end %>
</p>

<p>
  <strong>Hours:</strong>
  <%# iterates through inkindentry for this field %>
  <% @inkind.inkindentries.each do |donation| %>
    <%= donation.hours.present? ? "#{donation.hours}" : "" %>
    <br>
  <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @inkind.user %>
</p>

<p>
  <strong>Type:</strong>
  <%= @inkind.genre %>
</p>

<p>
  <strong>Donor:</strong>
  <%= @inkind.donor_name %>
</p>

<p>
  <strong>Donor ID:</strong>
  <%= @inkind.donor_id %>
</p>
<%= link_to 'Edit', edit_inkind_path(@inkind) %> |
<%= link_to 'View Inkind Donations', inkinds_path %>