src/config/routes.rb
# Project name: ACCR Mail Manager
# Description: Mail database and management system for ACCR community partner
# Filename: routes.rb
# Description: Configuration file for Rails page routes
# Last modified on: 3/26/23
# Code written by Team 13, Team 14, and Team 24

# Project name: AMSTR
# Description: ACCR Management System Tracker
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options
# Last modified on: 4/13/22

# Project name: Call Organizer
# Description: This project will keep track of the various calls ACCR recieves.
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options.
# Last modified on: 04/23/2023

# frozen_string_literal: true


# frozen_string_literal: true
# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

   get 'calls_home/index'
  resources :calls

  
  get 'speaker/all'
  get 'speaker/delete'
  post 'speaker/show'
  post 'webinars/deregisterSubmitted'
  get 'webinars/deregisterSubmitted'
  get 'speaker/new'
  post 'speaker/created'

  get 'requests/viewrequests'
  get 'webinars/deregister'
  

  resources :requests

  get 'webinars/exportCSV'
  post 'webinars/exportCSV'


  get 'charges/new'
  get 'charges/create'
  post 'exportCSV', to: 'webinars#exportCSV', as: 'exportCSV'

# delete from here if problem

  resources :donors
  resources :donars
  get 'in_kinds_home/index'
  get 'inkinds/index'


  
  resources :inkinds  do
    collection do
      get 'download_pdf'
    end
  end


  #pro-bono donations
  get 'donations/donations'
  get '/donations.csv' => 'donations#index'
  match 'donations', to: 'donations#donations', via: 'get'
  resources :donations do
    collection do
      post :import
    end
  end

  resources :event_details
  get 'calendar/calendar'

# to here

  resources :registrants
  resources :responses
  resources :reminders
  resources :webinars do
    member do
      get :registrants
    end
  end
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'webinars/index'
  get 'webinars/about'
  # does not need devise login
  # get 'webinarjoin', to: "webinarjoin#index"
  

  # routes for speaker information page
  get 'speaker/index'

  # The root page is set for the index.
  ### root 'home#index'
  get 'mail_manager_home/index'

  # Routes for pages other than the root.
  get 'mail_manager_home/about'

  # All pages associated with mail_entries and tags scaffold.
  resources :mail_entries
  resources :tags

  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # Custom routes for adding / deleting tags en masse.
  post 'delete_selected' => 'tags#delete_selected'
  post 'create_entered' => 'tags#create_entered'
  # post 'tag_filter' => 'mail_entries#'


  get 'statistics/index'
  resources :worklogs
  resources :projects

  resources :searches do
    get "search", on: :collection
  end

  root 'nav#home'

  get 'dashboard/dash'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard/dash'
  get 'dashboard/view_report'
  get 'home/index'
  get 'report/index'
  get 'dashboard/aboutus'


  

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  post "/map/index" => "map#index"
  # root 'home#index'
  get 'mapping_justice_home/index'
  get 'map/graph'
  get 'map/index'
  get 'about/index'
  get 'upload/index'
  post 'upload/uploadcsv'
  get 'upload/downloadcsv'
  get 'upload/edit'
  post 'upload/update'
  patch 'upload/:format', to: 'upload#update'
  get 'upload/destroy'
  #patch 'upload/:format', to: 'upload#destroy'

  #Used for clearing sorting
  get "/donations/clear_sort", to: "donations#clear_sort", as: "clear_sort"
  
  get "/donations/filtering", to: "donations#filtering", as: "filtering"

  get 'in_kinds_home/index'
  get 'donors/index'
  # Used for webinar registration forms
  get 'registrants/new' # Links to form input page
  get 'registrants/index'
  post 'registrants/new', to: 'registrants#create' # Creates post route for submitting form
  patch 'registrants/:id/activate',to:'registrants#activate' , as: :activate
  patch 'registrants/:id/deactivate',to:'registrants#deactivate' ,as: :deactivate
  
  get '/payment', to: 'payment_controller#blank_page'
  
  
    #get '/', to: 'register#index'
    #post '/orders/submit', to: 'orders#submit'
  
  # Devise authentification pages. This controlls the user login
  # and authentification system.

  # commented out due to rake aborted error
  # devise_for :users

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  #root 'home#index'

  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'

  # stripe
  resources :charges, only: [:new, :create, :thanks]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  
end

src/app/models/webinar.rb
=begin
Project name: ACCR Webinar
Description: This project will keep track of the webinars and their respective speakers.
Filename: webinar.rb
Description: Handles creation of the CSV file.
Last modified on: April 22, 2023
=end

class Webinar < ApplicationRecord
  has_and_belongs_to_many :registrants

  def start_time
    self.date_and_time
  end
  def self.to_csv(items = nil)
    attributes = %w{WebinarName Description Date+Time Speaker(s) RegistrantName Email CLEID Deregisterd County Job Listerv Topics } 
    if items.nil?
      items = Webinar.all
    end
    CSV.generate(headers: true) do |csv|
      csv << attributes
      
      items.each do |item|
        speakers = WebinarsSpeaker.select(:speaker_id).where(webinar_id:item.id)
        registrants = RegistrantsWebinar.select(:registrant_id).where(webinar_id:item.id)
        speakersCSV = []
        registrantsCSV = []
        speakers.each do |speaker|
          speakersCSV << Speaker.find_by(id:speaker.speaker_id).name
        end
        csv << [item.webinar_name, item.description, item.date_and_time, speakersCSV]

        registrants.each do |registrant|
          person = Registrant.find_by(id:registrant.registrant_id)
          csv << ["", "", "", "","#{person.first_name} #{person.last_name}", person.email, person.cleID, person.deregistered, person.county, person.job, person.listserv, person.topics ]
        end

      end
    end
  end
  
end

src/app/models/webinar_form.rb
class WebinarForm < ApplicationRecord

end

src/app/controllers/webinars_controller.rb
=begin
Project name: ACCR Webinar
Description: This project will keep track of the webinars and their respective speakers.
Filename: webinars_controller.rb
Description: Handles creation and updating of webinars
Last modified on: April 22, 2023
=end

# class WebinarsController < ApplicationController
#   before_action :set_webinar, only: %i[ show edit update destroy ]
#   skip_before_action :authenticate_user!, only: [:show, :index]

#   # GET /webinars or /webinars.json
#   def index
#     @webinars = Webinar.all
#   end

#   # GET /webinars/1 or /webinars/1.json
#   def show
#   end

#   def registrants
#     @webinars = Webinar.find(params[:id])
#   end


#   # GET /webinars/new
#   def new
#     @webinar = Webinar.new
#   end

#   # GET /webinars/1/edit
#   def edit
#   end

#   # POST /webinars or /webinars.json
#   def create
#     @webinar = Webinar.new(webinar_params)

#     respond_to do |format|
#       if @webinar.save
#         format.html { redirect_to webinar_url(@webinar), notice: "Webinar was successfully created." }
#         format.json { render :show, status: :created, location: @webinar }
#       else
#         format.html { render :new, status: :unprocessable_entity }
#         format.json { render json: @webinar.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /webinars/1 or /webinars/1.json
#   def update
#     respond_to do |format|
#       if @webinar.update(webinar_params)
#         format.html { redirect_to webinar_url(@webinar), notice: "Webinar was successfully updated." }
#         format.json { render :show, status: :ok, location: @webinar }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @webinar.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /webinars/1 or /webinars/1.json
#   def destroy
#     @webinar.destroy

#     respond_to do |format|
#       format.html { redirect_to webinars_url, notice: "Webinar was successfully deleted." }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_webinar
#       @webinar = Webinar.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def webinar_params
#       params.require(:webinar).permit(:webinar_name, :description, :date_and_time, :speaker)
#     end
# end

class WebinarsController < ApplicationController
include WebinarsHelper
  before_action :set_webinar, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:show, :index, :deregister, :deregisterSubmitted]
    # GET /webinars or /webinars.json
  def index
    # date_and_time_range goes from January 1, 1900 until the current system time.
    date_and_time_range = Time.new(1900,1,1,0,0,0) .. Time.now

    @completed_webinars = Webinar.where(date_and_time: date_and_time_range).order(date_and_time: :DESC)
    @upcoming_webinars = Webinar.where.not(date_and_time: date_and_time_range).order(date_and_time: :ASC)

    @webinars = Webinar.all

    if user_signed_in? === false
      @webinar_id_array = Array.new()
      respond_to do |format|
        format.html 
        format.csv { send_data @webinars.to_csv, filename: "webinarALL#{DateTime.now.strftime("%m-%d-%Y-%H:%M")}.csv" }
      end
      return
    end

    registrant_relation = Registrant.where(email: current_user.email)
    registrant_id_array = registrant_relation.pluck(:id)
    puts "Registrant ID Array: #{registrant_id_array} \n\n\n"
    if registrant_id_array.empty?
      @webinar_id_array = Array.new()
      respond_to do |format|
        format.html 
        format.csv { send_data @webinars.to_csv, filename: "webinarALL#{DateTime.now.strftime("%m-%d-%Y-%H:%M")}.csv" }
      end
      return
    end

    @webinar_id_array = RegistrantsWebinar.where(registrant_id: registrant_id_array).pluck(:webinar_id)
    respond_to do |format|
      format.html 
      format.csv { send_data @webinars.to_csv, filename: "webinarALL#{DateTime.now.strftime("%m-%d-%Y-%H:%M")}.csv" }
    end
    return
  end

  def exportCSV
    items = Webinar.where(id: params[:webs])
      csv_data = Webinar.to_csv(items)
      send_data csv_data
  end

  # GET /webinars/1 or /webinars/1.json
  def show
    speakers_id_array = WebinarsSpeaker.where(webinar_id: params[:id]).pluck(:speaker_id)
    @speakers_name_array = Array.new()
    speakers_id_array.each do |speaker_id|
      @speakers_name_array.push(Speaker.find_by(id: speaker_id).name)
    end
  end

  def registrants

    @webinars = Webinar.find(params[:id])

  end

  # GET /webinars/new
  # Create 2D-array for HTML dropdown menu
  def new
    @webinar = Webinar.new
    speakers_array = Array.new()
  end

  # GET /webinars/1/edit
  def edit
  end

  # POST /webinars or /webinars.json
  # Use transactions to ensure the database maintains integerity
  # and rolls back to the previous stable state if any errors are 
  # raised unexpectedly.
  def create
    speakers_id_array = params[:webinar][:speakers]
    puts "Webinar Params: #{webinar_params.inspect} \n\n\n"
    is_successful = Webinar.transaction do
      @webinar = Webinar.create!(webinar_params.except(:speakers))
      if webinar_params[:webinar_name].squish.empty?
        @webinar.errors.add(:webinar_name, "cannot be blank.")
      end
      if speakers_id_array.length === 1
        @webinar.errors.add(:speakers, "cannot be blank.")
      end
      if @webinar.errors.any?
        raise ActiveRecord::Rollback
      end
      speakers_id_array.each() do |speaker_id|
        speaker_id = speaker_id.to_i
        if speaker_id != 0 # For some reason, sends in ID: 0 on first input
          WebinarsSpeaker.create!(webinar_id: @webinar.id, speaker_id: speaker_id.to_i)
        end
      end
    end
    respond_to do |format|
      if is_successful
        format.html { redirect_to webinar_url(@webinar), notice: "Webinar was successfully created." }
        format.json { render :show, status: :created, location: @webinar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webinars/1 or /webinars/1.json
  def update
    respond_to do |format|
      if @webinar.update(webinar_params)
        format.html { redirect_to webinar_url(@webinar), notice: "Webinar was successfully updated." }
        format.json { render :show, status: :ok, location: @webinar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webinars/1 or /webinars/1.json
  def destroy
    webinars_speakers = WebinarsSpeaker.where(webinar_id: @webinar.id)
    webinars_speakers.each() do |webinar_speaker|
      webinar_speaker.destroy
    end
    @webinar.destroy

    respond_to do |format|
      format.html { redirect_to webinars_url, notice: "Webinar was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def deregister
    @webID = params[:format]
    @name = Webinar.where(id: @webID).pluck(:webinar_name)[0]
    
  end

  def deregisterSubmitted
    @email = params[:email]
    @success = "no"
    registrant =  Registrant.where(email: @email)
    regID = registrant.pluck(:id)[0]
    if RegistrantsWebinar.where(registrant_id: regID, webinar_id: params[:webID]).exists?
      registrant.update(deregistered:"Yes" )
      @success = "yes"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webinar
      @webinar = Webinar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webinar_params
      params.require(:webinar).permit(:webinar_name, :description, :date_and_time, :speakers)
    end
end

src/app/helpers/webinars_helper.rb
module WebinarsHelper
    def checkWebinars
        if params[:webinar_ids].nil? == false
            puts "\n\n\n\n\n test \n\n\n"
            @webinars.each do |webinar|
                if params[:webinar_ids].include?(webinar.id.to_s)
                    Webinar.update(webinar.id, csvEntry:"1")
                else
                    Webinar.update(webinar.id, csvEntry:"0")
                end

            end
        end
    end  
end

src/app/views/webinars/_form.html.erb
<%
=begin  
# Project name: Webinars
# Description: Create form partial for entering data in database with associations
# Last Modified: April 22, 2023
=end
speakers_array = Array.new()
Speaker.all.each() do |speaker|
  speaker_array = Array.new()
  speaker_array.push(speaker.name)
  speaker_array.push(speaker.id)
  speakers_array.push(speaker_array)
end
%>

<div class="card">
  <div class="card-header">
    <h4>New Webinar</h4>
  </div>
  <div class="card-body">
    <%= form_with(model: webinar, local: true) do |form| %>
      <% if webinar.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(webinar.errors.count, "error") %> prohibited this webinar from being saved:</h2>
          <ul>
            <% webinar.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= form.label "Webinar Name:" %><br>
        <%= form.text_field :webinar_name %>
      </div>

      <div class="field form-group">
        <%= form.label "Webinar Description:" %><br>
        <%= form.text_area :description %>
      </div>

      <div class="field form-group">
        <%= form.label "Date and Time:"%><br>
        <%= form.datetime_select :date_and_time %>
      </div>

      <div class="field form-group">
        <label class="form-label", for="webinar_speakers">Speakers (drag to select multiple): </label>

        <br> Speaker not listed? Create a speaker here:
         <%= link_to "Create Speaker Form", speaker_new_path, class:"btn btn-primary btn-sm"%>

        <%= form.select :speakers, speakers_array, {}, {multiple: true, class: "form-select", id: "webinar_speakers"} %>
      </div>

      <div class="actions">
        <%= form.submit class:"btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

src/app/views/webinars/deregister.html.erb
<div class="card">
    <div class="card-header">
        <h4> Deregistration for <%= @name %> </h4> 
    </div>

    <div class= "card-body">
        <!-- FORM HERE -->
            <%= form_with url: webinars_deregisterSubmitted_path, id: "DR", method: :post, local: true do |form| %>
            
            <div class="field">
                <%= form.label "Email:" %></br>
                <%= form.text_field :email, id: 'DRemail' %>
              <%= form.hidden_field :webID, value:@webID %></div>
            <div class="actions">
            <br>
                <%= form.submit 'Submit', class:'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

src/app/views/webinars/deregisterSubmitted.html.erb
<%if @success == "yes"%>
Sucessfully Submitted.
<%else%>
Not Submitted. Please consider if you have registered for this webinar.
<%end%>
<br>
<br>
<%= link_to 'Back to webinars', webinars_path, class:"btn btn-primary"%>

src/app/views/webinars/edit.html.erb
<h1>Editing Webinar</h1>

<%= render 'form', webinar: @webinar %>

<%= link_to 'Back', webinars_path, class: "btn btn-primary" %> | 
<%= link_to 'Show', @webinar, class: "btn btn-primary" %>

src/app/views/webinars/index.html.erb
<%
=begin
Project name: ACCR Webinar
Description: This project will keep track of the webinars and their respective speakers.
Filename: webinars/index.html.erb
Description: Handles showing information about a webinar.
Last modified on: April 22, 2023
=end
%>
<p id="notice"><%= notice %></p>

<h2>Upcoming Webinars</h2>

<h6>Webinars you registered for will appear in green.</h6>

<%= form_tag exportCSV_path,  id: "CSV" do %>

<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Webinar Name</th>
      <th>Description</th>
      <th>Date and Time</th>
      <th>Speaker(s)</th>
      <th colspan="100%"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcoming_webinars.each do |webinar| %>
      <% if @webinar_id_array.include?(webinar.id) %>
        <tr class="table-success">
      <% else %>
        <tr>
      <% end %>
        <td><%= webinar.webinar_name %></td>
        <td><%= webinar.description %></td>
        <td><%= webinar.date_and_time.strftime("%B %d, %Y %I:%M%p") %></td>
        <td>
          <% speakers_info_array = WebinarsSpeaker.select(:speaker_id).where(webinar_id: webinar.id) %>
          <% speakers_info_array.each do |speaker_info| %>
            <%= link_to Speaker.find_by(id: speaker_info.speaker_id).name, speaker_show_path(speaker_info.speaker_id), method: :post %><br>
          <% end %>
        </td>
        <td><%= link_to 'Show', webinar_path(webinar), class:'btn btn-primary', method: :get %></td>
        <% if can?(:access, :rails_admin) %>
          <td><%= link_to 'Edit', edit_webinar_path(webinar), class:'btn btn-primary'  %></td>
          <td><%= link_to 'Delete', webinar, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary'  %></td>
          <td><%= link_to 'See registrants', registrants_webinar_path(webinar), class:'btn btn-primary'  %></td>
          <td><%= check_box_tag 'webs[]', webinar.id %></td> 
        <% else %>
          <td><%= link_to 'Register', new_registrant_path(webinar.id), class:'btn btn-primary' %></td>
          <td><%= link_to 'Deregister', webinars_deregister_path(webinar.id), class:'btn btn-primary' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<h2>Past Webinars</h2>

<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Webinar Name</th>
      <th>Description</th>
      <th>Date and Time</th>
      <th>Speaker(s)</th>
      <th colspan="100%"></th>
    </tr>
  </thead>

  <tbody>
    <% @completed_webinars.each do |webinar| %>
      <tr>
        <td><%= webinar.webinar_name %></td>
        <td><%= webinar.description %></td>
        <td><%= webinar.date_and_time.strftime("%B %d, %Y %I:%M%p") %></td>
        <td>
          <% speakers_info_array = WebinarsSpeaker.select(:speaker_id).where(webinar_id: webinar.id) %>
          <% speakers_info_array.each do |speaker_info| %>
            <%= link_to Speaker.find_by(id: speaker_info.speaker_id).name, speaker_show_path(speaker_info.speaker_id), method: :post %><br>
          <% end %>
        </td>
        <td><%= link_to 'Show', webinar, class:'btn btn-primary' %></td>
        <% if can?(:access, :rails_admin) %>
          <td><%= link_to 'Edit', edit_webinar_path(webinar), class:'btn btn-primary'  %></td>
          <td><%= link_to 'Delete', webinar, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary'  %></td>
          <td><%= link_to 'See registrants', registrants_webinar_path(webinar), class:'btn btn-primary'  %></td>
          <td><%= check_box_tag 'webs[]', webinar.id %></td> 
        <% else %>
          <td><%= link_to 'Register', new_registrant_path(webinar.id), class:'btn btn-primary' %></td>
          <td><%= link_to 'Deregister', webinars_deregister_path(webinar.id), class:'btn btn-primary' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can?(:access, :rails_admin) %>
  <%= submit_tag "EXPORT SELECTED CSV",id: 'export-btn', class:'btn btn-primary'  %>
  <%= link_to 'EXPORT ALL CSV', webinars_path(format:'csv'), class:'btn btn-primary' %>
<% end %>
<% end %>

<br>
<% if can?(:access, :rails_admin) %>
  <%= link_to 'New Webinar', new_webinar_path, class:'btn btn-primary' %>
<% end %>

<%= link_to 'View Event Calendar', event_details_path, class:'btn btn-primary' %>

<script>
  document.getElementById('CSV').addEventListener('submit', function(event) {
    event.preventDefault();
    exportCsv();
  });

  function exportCsv() {
    var form = document.getElementById('CSV');
    var data = new FormData(form);
    var xhr = new XMLHttpRequest();

    xhr.open('POST', form.action, true);
    xhr.responseType = 'blob';
    const dateObject = new Date();

    let date = dateObject.toUTCString();

    xhr.onload = function() {
      if (xhr.status === 200) {
        var a = document.createElement('a');
        var url = window.URL.createObjectURL(xhr.response);
        a.href = url;
        a.download = `webinar${date}.csv`;
        document.body.appendChild(a);
        a.click();
        setTimeout(function() {
          document.body.removeChild(a);
          window.URL.revokeObjectURL(url);
          document.getElementById('export-btn').disabled = false;
        }, 100);
      }
    };

    xhr.send(data);
    document.getElementById('export-btn').disabled = true;
  }
</script>

src/app/views/webinars/new.html.erb
<%= render 'form', webinar: @webinar %>
</br>
<%= link_to 'Back', webinars_path %>

src/app/views/webinars/registrants.html.erb
<!-- Team 12 -->
<!-- Modified on 4/27/23 -->

<h3>Registrants for the <%= @webinars.webinar_name %> Webinar</h3>


<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
       <th>State</th>
      <th>County</th>
      <th>CLE ID</th>
      <th>Job</th>
      <th>Listserv</th>
      <th>Topics</th>
      <th>Deregistered?</th>
      <th>Paid</th>
      <th>Amount</th>
      <th>Deregistered?</th>
      <th colspan="100%"></th>

    </tr>
  </thead>

  <tbody>
    <% @webinars.registrants.each do | registrant | %>
      <tr>
        <td><%= registrant.first_name %></td>
        <td><%= registrant.last_name %></td>
        <td><%= registrant.email %></td>
        <td><%= registrant.state %></td>
        <td><%= registrant.county %></td>
        <td><%= registrant.cleID %></td>
        <td><%= registrant.job %></td>
        <td><%= registrant.listserv %></td>
        <td><%= registrant.topics %></td>
        <td><%= registrant.deregistered %></td>
<td><%= registrant.paid %></td>
<td><%= number_to_currency(registrant.amount) %></td>
<td><%= link_to 'Delete', registrant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %></td>


     
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Webinars', "/webinars", class:'btn btn-primary' %>

src/app/views/webinars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card text-center">
  <div class="card-header">
    Webinar
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @webinar.webinar_name %></h5>
    <p class="card-text">
    <%= @webinar.description %><br><br>
    </p>
    <p class="card-text">

      Speakers:<br>
      <% if @speakers_name_array.any? %>
        <% @speakers_name_array.each() do |speaker_name| %>
          <%= speaker_name %><br>
        <% end %>
      <% else %>
        There are no speakers for this webinar yet.
      <% end %>

    </p>
  </div>
  <div class="card-footer text-muted">
    <%= @webinar.date_and_time.strftime("%B %d, %Y %I:%M%p") %>
  </div>
</div>

</br>
<%= link_to 'Back', webinars_path, class:'btn btn-primary' %>
<% if can?(:access, :rails_admin) %>
| <%= link_to 'Edit', edit_webinar_path(@webinar), class:'btn btn-primary' %>
<% end %>

src/app/views/webinars/test.html.erb
HI