src/config/routes.rb
# Project name: ACCR Mail Manager
# Description: Mail database and management system for ACCR community partner
# Filename: routes.rb
# Description: Configuration file for Rails page routes
# Last modified on: 3/26/23
# Code written by Team 13, Team 14, and Team 24

# Project name: AMSTR
# Description: ACCR Management System Tracker
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options
# Last modified on: 4/13/22

# Project name: Call Organizer
# Description: This project will keep track of the various calls ACCR recieves.
# Filename: routes.rb
# Description: Configuration file for actions/routes of user options.
# Last modified on: 04/23/2023

# frozen_string_literal: true


# frozen_string_literal: true
# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

   get 'calls_home/index'
  resources :calls

  
  get 'speaker/all'
  get 'speaker/delete'
  post 'speaker/show'
  post 'webinars/deregisterSubmitted'
  get 'webinars/deregisterSubmitted'
  get 'speaker/new'
  post 'speaker/created'

  get 'requests/viewrequests'
  get 'webinars/deregister'
  

  resources :requests

  get 'webinars/exportCSV'
  post 'webinars/exportCSV'


  get 'charges/new'
  get 'charges/create'
  post 'exportCSV', to: 'webinars#exportCSV', as: 'exportCSV'

# delete from here if problem

  resources :donors
  resources :donars
  get 'in_kinds_home/index'
  get 'inkinds/index'


  
  resources :inkinds  do
    collection do
      get 'download_pdf'
    end
  end


  #pro-bono donations
  get 'donations/donations'
  get '/donations.csv' => 'donations#index'
  match 'donations', to: 'donations#donations', via: 'get'
  resources :donations do
    collection do
      post :import
    end
  end

  resources :event_details
  get 'calendar/calendar'

# to here

  resources :registrants
  resources :responses
  resources :reminders
  resources :webinars do
    member do
      get :registrants
    end
  end
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'webinars/index'
  get 'webinars/about'
  # does not need devise login
  # get 'webinarjoin', to: "webinarjoin#index"
  

  # routes for speaker information page
  get 'speaker/index'

  # The root page is set for the index.
  ### root 'home#index'
  get 'mail_manager_home/index'

  # Routes for pages other than the root.
  get 'mail_manager_home/about'

  # All pages associated with mail_entries and tags scaffold.
  resources :mail_entries
  resources :tags

  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # Custom routes for adding / deleting tags en masse.
  post 'delete_selected' => 'tags#delete_selected'
  post 'create_entered' => 'tags#create_entered'
  # post 'tag_filter' => 'mail_entries#'


  get 'statistics/index'
  resources :worklogs
  resources :projects

  resources :searches do
    get "search", on: :collection
  end

  root 'nav#home'

  get 'dashboard/dash'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'dashboard/dash'
  get 'dashboard/view_report'
  get 'home/index'
  get 'report/index'
  get 'dashboard/aboutus'


  

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  post "/map/index" => "map#index"
  # root 'home#index'
  get 'mapping_justice_home/index'
  get 'map/graph'
  get 'map/index'
  get 'about/index'
  get 'upload/index'
  post 'upload/uploadcsv'
  get 'upload/downloadcsv'
  get 'upload/edit'
  post 'upload/update'
  patch 'upload/:format', to: 'upload#update'
  get 'upload/destroy'
  #patch 'upload/:format', to: 'upload#destroy'

  #Used for clearing sorting
  get "/donations/clear_sort", to: "donations#clear_sort", as: "clear_sort"
  
  get "/donations/filtering", to: "donations#filtering", as: "filtering"

  get 'in_kinds_home/index'
  get 'donors/index'
  # Used for webinar registration forms
  get 'registrants/new' # Links to form input page
  get 'registrants/index'
  post 'registrants/new', to: 'registrants#create' # Creates post route for submitting form
  patch 'registrants/:id/activate',to:'registrants#activate' , as: :activate
  patch 'registrants/:id/deactivate',to:'registrants#deactivate' ,as: :deactivate
  
  get '/payment', to: 'payment_controller#blank_page'
  
  
    #get '/', to: 'register#index'
    #post '/orders/submit', to: 'orders#submit'
  
  # Devise authentification pages. This controlls the user login
  # and authentification system.

  # commented out due to rake aborted error
  # devise_for :users

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  #root 'home#index'

  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'

  # stripe
  resources :charges, only: [:new, :create, :thanks]
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  
end

src/app/models/event_detail.rb
# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: event_detail.rb
# Description: the the data model for each event detail renndered by the calenndar
# Last modified on: 11/10/2022
class EventDetail < ApplicationRecord

    #uses active record to store one banner image per event detail
    has_one_attached :banner
    
    class MyModel
        ## Other code related to your model lives here
    end

end

src/app/controllers/event_details_controller.rb
# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: event_details_controller.rb
# Description: controls the calendar display and events crud features
# Last modified on: 11/10/2022 (added :banner to event_detail params)

class EventDetailsController < ApplicationController
  before_action :set_event_detail, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:show, :index]


  # GET /event_details or /event_details.json
  def index
    @event_details = EventDetail.all
    @webinars = Webinar.all
    
  end

  # GET /event_details/1 or /event_details/1.json
  def show
  end

  # GET /event_details/new
  def new
    @event_detail = EventDetail.new
  end

  # GET /event_details/1/edit
  def edit
  end

  # POST /event_details or /event_details.json
  def create
    @event_detail = EventDetail.new(event_detail_params)

    respond_to do |format|
      if @event_detail.save
        format.html { redirect_to event_detail_url(@event_detail), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_details/1 or /event_details/1.json
  def update
    respond_to do |format|
      if @event_detail.update(event_detail_params)
        format.html { redirect_to event_detail_url(@event_detail), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_details/1 or /event_details/1.json
  def destroy
    @event_detail.destroy

    respond_to do |format|
      format.html { redirect_to event_details_url, notice: "Event was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_detail
      @event_detail = EventDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_detail_params
    
      params.require(:event_detail).permit(:title, :start_time, :end_time, :speakers, :description, :event_link, :created_by, :banner)

    end
end

src/app/helpers/event_details_helper.rb
module EventDetailsHelper
end

src/app/views/event_details/_form.html.erb
<!--# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: _form.html.erb
# Description:  all input necessary to create or edit an event, this form is rendered in a few places
# Last modified on: 11/14/2022-->

<%= form_with(model: event_detail, local: true) do |form| %>
  <% if event_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_detail.errors.count, "error") %> prohibited this event_detail from being saved:</h2>

      <ul>
        <% event_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.label "Event Banner" %>
  <%= form.file_field :banner, :accept => 'image/png, image/jpeg' %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :speakers %>
    <%= form.text_area :speakers %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


  <div class="field">
    <%= form.label :event_link %>
    <%= form.text_field :event_link %>
  </div>

  <div class="field">
    <%= form.label :created_by %>
    <%= form.text_field :created_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/event_details/edit.html.erb
<!--# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: edit.html.erb
# Description:  edit an event
# Last modified on: 10/25/2022-->

<h1>Editing Event</h1>

<%= render 'form', event_detail: @event_detail %>

<%= link_to 'Show', @event_detail %> |
<%= link_to 'Back', event_details_path %>

src/app/views/event_details/index.html.erb
<!--# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: index.html.erb
# Description: the calendars main page that displays options for admins to 
# create, edit, and destroy events that appear on the calendar
# Last modified on: 11/14/2022-->

<p id="notice"><%= notice %></p>

<h1 class="text-center"> Rails of Justice: Event Calendar </h1>

<%= month_calendar(events: @webinars) do |date, webinars| %>
  <%= date.day %>

  <!--maps events to be displayed in calendar as links to their respective pages-->
  <% webinars.each do |webinar| %>
    <div>
      <%= link_to webinar.webinar_name, webinar %>
    </div>
  <% end %>
<% end %>

<table class="table table-striped" style="width:100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Event Date & Time</th>
      <th>Speakers</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @webinars.each do |webinar| %>
      <tr>
        <td><%= webinar.webinar_name %></td>

        <td><%= webinar.date_and_time.strftime("%B %d, %Y %I:%M%p") %></td>
        <td><% speakers_info_array = WebinarsSpeaker.select(:speaker_id).where(webinar_id: webinar.id) 
               speakers_info_array.each() do |speaker_info| %>
            <%= link_to Speaker.find_by(id: speaker_info.speaker_id).name, speaker_show_path(speaker_info.speaker_id), method: :post %><br>
               <% end %></td>
        <td><%= webinar.description %></td>
        <td><%= link_to 'Show', webinar, class:'btn btn-primary' %></td>
        <td><%= link_to 'Register', new_registrant_path(webinar.id), class:'btn btn-primary' %></td>
        <% if can?(:access, :rails_admin) %>
        <td><%= link_to 'Edit', edit_webinar_path(webinar), class:'btn btn-primary'  %></td>
        <td><%= link_to 'Delete', webinar, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary'  %></td>
	      <td> <%= link_to 'See registrants', registrants_webinar_path(webinar), class:'btn btn-primary'  %> </td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<% if can?(:access, :rails_admin) %>
<%= link_to 'New Event', new_event_detail_path, class: "btn btn-outline-primary" %>
<%= link_to 'New Webinar', new_webinar_path, class: "btn btn-outline-primary" %>
<% end %>
<% else %>
<% end %><!--hides this view from non-admins-->

src/app/views/event_details/new.html.erb
<!--# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: new.html.erb
# Description: creates a new event
# Last modified on: 10/25/2022-->

<h1>New Event Detail</h1>

<%= render 'form', event_detail: @event_detail %>

<%= link_to 'Back', event_details_path %>

src/app/views/event_details/show.html.erb
<!--# Project name: Event Calendar
# Description: Provides a calendar view to help defense attorneys schedule their webinars.
# Filename: show.html.erb
# Description:  displays deatils about an event
# Last modified on: 11/14/2022-->
<p id="notice"><%= notice %></p>

<!--render banner image using active record-->
<% if @event_detail.banner.attached? %>
  <img style="width:35%" src="<%=(url_for(@event_detail.banner))%>">
<% end %>

<p>
  <strong>Title:</strong>
  <%= @event_detail.title %>
</p>

<p>
  <strong>Event Date & Time:</strong>
  <%= @event_detail.start_time.strftime("%b %d %I:%M %P") %>
</p>

<p>
  <strong>Event Date & Time:</strong>
  <%= @event_detail.end_time.strftime("%b %d %I:%M %P") %>
</p>

<p>
  <strong>Speakers:</strong>
  <%= @event_detail.speakers %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event_detail.description %>
</p>

<p>
  <strong>Event Link:</strong>
  <%= link_to 'Click Here', "https://#{@event_detail.event_link}", :target => '_blank'%>
</p>

<%= link_to 'Training Registration',  registrants_new_path, class: "btn btn-primary btn-sm", method: :get %>

<% if can?(:access, :rails_admin) %>
  <%= link_to 'Edit', edit_event_detail_path(@event_detail) %> |
<% end %>
<%= link_to 'Back', event_details_path %>